---
title: "Notes - Chetty et al. (2014) - QJE"
subtitle: "Where is the Land of Opportunity? The Geography of Intergenerational Mobility in the US"
author: "Lucas Warwar" 
date: "`r Sys.Date()`"
bibliography: 
output: 
  pdf_document:
    latex_engine: xelatex
citation_package: natbib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Notes of [Chetty et al., 2014](https://academic.oup.com/qje/article/129/4/1553/1853754)

# Introduction
----------

## Intergenerational Mobility in the US

We characterize intergenerational mobility using information from deidentified federal income tax records, which provide data on the incomes of more than 40 million children and their parents between 1996 and 2012. We focus on U.S. citizens in the 1980–1982 birth cohorts. We measure these children’s income as mean total family income in 2011 and 2012, when they are approximately 30 years old. We measure their parents’ income as mean family income between 1996 and 2000, when the children are between the ages of 15 and 20.

To obtain a more stable summary of intergenerational mobility, we use a rank-rank specification similar to that used by Dahl and DeLeire (2008). We rank children based on their incomes relative to other children in the same birth cohort. We rank parents of these children based on their incomes relative to other parents with children in these birth cohorts. We characterize mobility based on the slope of this rank-rank relationship, which identifies the correlation between children’s and parents’ positions in the income distribution.

We find that the relationship between mean child ranks and parent ranks is almost perfectly linear and highly robust to alternative specifications. A 10 percentile point increase in parent rank is associated with a 3.41 percentile increase in a child’s income rank on average. Children’s college attendance and teenage birth rates are also linearly related to parent income ranks. A 10 percentile point increase in parent income is associated with a 6.7 percentage point (pp) increase in college attendance rates and a 3 pp reduction in teenage birth rates for women.

## Variation in mobility accross commuting zones (CZ's)

We assign children to CZs based on where they lived at age 16—that is, where they grew up—irrespective of whether they left that CZ afterward. The relationship between mean child ranks and parent ranks is almost perfectly linear within CZs, allowing us to summarize the conditional expectation of a child’s rank given his parents’ rank with just two parameters: a slope and intercept. The slope measures relative mobility: the difference in outcomes between children from top versus bottom income families within a CZ. The intercept measures the expected rank for children from families at the bottom of the income distribution. Combining the intercept and slope for a CZ, we can calculate the expected rank of children from families at any given percentile p of the national parent income distribution. We call this measure absolute mobility at
percentile p. 

We find substantial variation in both relative and absolute mobility across CZs. Relative mobility is lowest for children who grew up in the Southeast and highest in the Mountain West and the rural Midwest. Some CZs in the United States have relative mobility comparable to the highest mobility countries in the world, such as Canada and Denmark, while others have lower levels of mobility than any developed country for which data are available.

We find similar geographical variation in absolute mobility. We focus much of our analysis on absolute mobility at p = 25, which we call ‘‘absolute upward mobility.’’ This statistic measures the mean income rank of children with parents in the bottom half of the income distribution given linearity of the rank-rank relationship. Absolute upward mobility ranges from 35.8 in Charlotte to 46.2 in Salt Lake City among the 50 largest CZs. Other measures of upward mobility exhibit similar spatial variation. For instance, the probability that a child reaches the top fifth of the income distribution conditional on having parents in the bottom fifth is 4.4% in Charlotte, compared with 10.8% in Salt Lake City and 12.9% in San Jose. The CZ-level mobility statistics are robust to adjusting for differences in the local cost of living, shocks to local growth, and using alternative measures of income.

The spatial patterns of the gradients of college attendance and teenage birthrates with respect to parent income across CZs are very similar to the variation in intergenerational income mobility. This suggests that the spatial differences in mobility are driven by factors that affect children while they are growing up rather than after they enter labor market.

## Characteristcs related to upward mobility

We then identify five factors that are strongly correlated with the variation in upward mobility across areas. The first is segregation: areas that are more residentially segregated by race and income have lower levels of mobility. Second, areas with more inequality as measured by Gini coefficients have less mobility, consistent with the ‘‘Great Gatsby curve’’ documented across countries (Krueger 2012; Corak 2013). Third, proxies for the quality of the K-12 school system are positively correlated with mobility. Fourth, social capital indexes (Putnam 1995) — which are proxies for the strength of social networks and community involvement in an area—are also positively correlated with mobility. 

Finally, mobility is significantly lower in areas with weaker family structures, as measured, for example, by the fraction of single parents. We find modest correlations between upward mobility and local tax policies and no systematic correlation between mobility and local labor market conditions, rates of migration, or access to higher education. In a multivariable regression, the five key factors described above generally remain statistically significant predictors of both relative and absolute upward mobility, even in specifications with state fixed effects. 

However, we emphasize that these factors should not be interpreted as causal determinants of mobility because all of these variables are endogenously determined and our analysis does not control for numerous other unobserved differences across areas. In a followup paper, Chetty and Hendren (2014) show that a substantial portion of the spatial variation documented here is driven by causal effects of place by studying families that move across areas with children of different ages.

# Measures of Intergenerational Mobility
-------------------

## Relative Mobility

One way to study intergenerational mobility is to ask, ‘‘What are the outcomes of children from low-income families relative to those of children from high-income families?’’ This question focuses on the relative outcomes of children from different parental backgrounds. 

The canonical measure of relative mobility is the elasticity of child income with respect to parent income, commonly called the intergenerational income elasticity (IGE). The most common method of estimating the IGE is to regress log child income on log parent income, which yields a coefficient of IGE that is a relative mobility measure because it measures the difference in (log) outcomes between children of high versus low income parents.

An alternative measure of relative mobility is the correlation between child and parent percentile ranks in the income distribution. Regressing the child’s rank on his parents’ rank yields a regression coefficient which we call the rank-rank slope. The rank-rank slope measures the association between a child’s position in the income distribution and his parents’ position in the distribution. To understand the connection between the IGE and the rankrank slope, note that the correlation of log incomes and the correlation of ranks are closely related scale-invariant measures of the degree to which child income depends on parent income. The IGE differs from the rank-rank slope to the extent that inequality changes across generations. Intuitively, a given increase in parents’ incomes has a greater effect on the level of children’s incomes when inequality is greater among children than among parents.

## Absolute Mobility

A different way to measure intergenerational mobility is to ask, ‘‘What are the outcomes of children from families of a given income level in absolute terms?’’ For example, one may be interested in measuring the mean outcomes of children whose grow up in low-income families. Absolute mobility may be of greater normative interest than relative mobility. Increases in relative mobility (i.e., a lower IGE or rank-rank slope) could be undesirable if they are caused by worse outcomes for the rich. In contrast, increases in absolute mobility at a given income level, holding fixed absolute mobility at other income levels, unambiguously increase welfare if one respects the Pareto principle.

We consider three statistical measures of absolute mobility. Our primary measure, which we call absolute upward mobility, is the mean rank (in the national child income distribution) of children whose parents are at the 25th percentile of the national parent income distribution. At the national level, this statistic is mechanically related to the rank-rank slope and does not provide any additional information about mobility. However, when we study small areas within the United States, a child’s rank in the national income distribution is effectively an absolute outcome because incomes in a given area have little effect on the national distribution.

The second measure we analyze is the probability of rising from the bottom quintile to the top quintile of the income distribution, which can be interpreted as a measure of the fraction of children who achieve the ‘‘American Dream.’’ Again, when the quintiles are defined in the national income distribution, these transition probabilities can be interpreted as measures of absolute outcomes in small areas.

Our third measure is the probability that a child has family income above the poverty line conditional on having parents at the 25th percentile. Because the poverty line is defined in absolute dollar terms in the United States, this statistic measures the fraction of children who achieve a given absolute living standard.

# Data
--------------

## Sample Definitions

Our base data set of children consists of all individuals who (i) have a valid Social Security number or individual taxpayer identification number, (ii) were born between 1980 and 1991, and (iii) are U.S. citizens as of 2013. We identify the parents of a child as the first tax filers (between 1996 and 2012) who claim the child as a child dependent and were between the ages of 15 and 40 when the child was born. If the child is first claimed by a single filer, the child is defined as having a single parent. We are therefore able to identify parents for approximately 95 percent of the children in the 1980–1991 birth cohorts. The fraction of children linked to parents drops sharply prior to the 1980 birth cohort because our data begin in 1996 and many children begin to the leave the household starting at age 17. This is why we limit our analysis to children
born during or after 1980.

Our primary analysis sample, which we refer to as the core sample, includes all children in the base data set who (i) are born in the 1980–1982 birth cohorts, (ii) for whom we are able to identify parents, and (iii) whose mean parent income between 1996 and 2000 is strictly positive (which excludes 1.2% of children). For some robustness checks, we use the extended sample, which imposes the same restrictions as the core sample, but includes all birth cohorts from 1980 to 1991. There are approximately 10 million children in the core sample and 44 million children in the extended sample.

## Variables Definitions and Summary Statistics

*Parental Income*: our primary measure of parent income is total pretax income at the household level, which we label parent family income. Our baseline income measure includes labor earnings and capital income as well as unemployment insurance, Social Security, and disability benefits. It excludes nontaxable cash transfers such as Temporary Assistance to Needy Families and Supplemental Security Income, in-kind benefits such as food stamps, all refundable tax credits such as the EITC, nontaxable pension contributions, and any earned income not reported to the IRS. Income is always measured prior to the deduction of individual income taxes and employee-level payroll taxes. In our baseline analysis, we average parents’ family income over the five years from 1996 to 2000 to obtain a proxy for parent lifetime income that is less affected by transitory fluctuations. We use the earliest years in our sample to best reflect the economic resources of parents while the children in our sample are growing up.

*Child Income*: We define child family income in the same way as parent family income. In our baseline analysis, we average child family income over the last two years in our data (2011 and 2012), when children are in their early thirties. We report results using alternative years to assess the sensitivity of our findings. For children, we define household income based on current marital status rather than marital status at a fixed point in time.

*College Attendance*: We define college attendance as an indicator for having one or more 1098-T forms filed on one’s behalf when the individual is aged 18–21. Title IV institutions—all colleges and universities as well as vocational schools and other postsecondary institutions eligible for federal student aid—are required to file 1098-T forms that report tuition payments or scholarships received for every student.

*College Quality*: Using data from 1098-T forms, Chetty, Friedman, and Rockoff (2014) construct an earnings-based index of ‘‘college quality’’ using the mean individual wage earnings at age 31 of children born in 1979–1980 based on the college they attended at age 20. Children who do not attend college are included in a separate ‘‘no college’’ category in this index. 

*Teenage Birth*: We define a woman as having a teenage birth if she ever claims a dependent who was born while she was between the ages of 13 and 19. This measure is an imperfect proxy for having a teenage birth because it only covers children who are claimed as dependents by their mothers. Nevertheless, the aggregate level and spatial pattern of teenage births in our data are closely aligned with estimates based on the American Community Survey.

*Summary Statistics*: Median parent family income is $60,129 (in 2012 dollars). Among the 30.6% of children matched to single parents, 72.0% are matched to a female parent. Children in our core sample have a median family income of $34,975 when they are approximately 30 years old; 6.1% of children have zero income in both 2011 and 2012; 58.9% are enrolled in a college at some point between the ages of 18 and 21; and 15.8% of women have a teenage birth. The total cohort size, labor force participation rate, distribution of child income, and other demographic characteristics of our core sample line up closely with corresponding estimates in the Current Population Survey and American Community Survey. This confirms that our sample covers roughly the same nationally representative population.

# National Statistics

## Baseline Estimates

Figure I Panel A presents a binned scatter plot of the mean family income of children versus the mean family income of their parents. To construct this figure, we divide the horizontal axis into 100 equal-sized (percentile) bins and plot mean child income versus mean parent income in each bin. This binned scatter plot provides a nonparametric representation of the conditional expectation of child income given parent income. The regression coefficients and standard errors reported in this and all subsequent binned scatter plots are estimated on the underlying microdata using OLS regressions. The conditional expectation of children’s income given parents’ income is strongly concave. Below the 90th percentile of parent income, a $1 increase in parent family income is associated with a 33.5 cent increase in average child family income. In contrast, between the 90th and 99th percentile, a $1 increase in parent income is associated with only a 7.6 cent increase in child income.

### Rank-Rank Estimates

Figure II Panel A presents a binned scatter plot of the mean percentile rank of children E[RijPi ¼ p] versus their parents’ percentile rank p. The conditional expectation of a child’s rank given his parents’ rank is almost perfectly linear. Using an OLS regression, we estimate that a 1 percentage point (pp) increase in parent rank is associated with a 0.341 pp increase in the child’s mean rank.

### Transition Matrix

Table II presents a quintile transition matrix: the probability that a child is in quintile m of the child income distribution conditional on his parent being in quintile n of the parent income distribution. One statistic of particular interest in this matrix is the probability of moving from the bottom quintile to the top quintile, a simple measure of success that we return to later. This probability is 7.5% in the United States.

## Robustness of Baseline Estimates

### Life Cycle Bias

Prior research has shown that measuring children’s income at early ages can understate intergenerational persistence in lifetime income because children with high lifetime incomes have steeper earnings profiles when they are young. To evaluate whether our baseline estimates suffer from such life cycle bias, Figure III Panel A plots estimates of the rank-rank slope by the age at which the child’s income is measured.

We construct the series in circles by measuring children’s income as mean family income in 2011–2012 and parent income as mean family income between 1996 and 2000, as in our baseline analysis. We then replicate the OLS regression of child income rank on parent income rank for each birth cohort between 1980 and 1990. For children in the 1980 birth cohort, we measure earnings in 2011-2012 at age 31–32 (denoted by 32 in the figure); for the 1990 cohort, we measure earnings at age 21–22.27 The rank-rank slope rises very steeply in the early twenties as children enter the labor force, but stabilizes around age 30. It increases by 2.1% from age 30 to 31 and 0.2% from age 31 to 32. After age 32, the estimates remain roughly constant. These findings indicate that rank-rank correlations exhibit little life cycle bias provided that child income is measured after age 30, as in our baseline definition.

An analogous life cycle bias can arise if parent income is measured at very old or young ages. In Online Appendix Figure II Panel B we plot the rank-rank slope using the core sample, varying the five-year window used to measure parent income from a starting year of 1996 (when mothers are 41 years old on average) to 2010 (when mothers are 55 years old). The rank-rank estimates exhibit virtually no variation with the age of parent income measurement within this range.

A closely related concern is that parent income at earlier ages might matter more for children’s outcomes, for example, if resources in early childhood are relevant for child development. In Chetty et al. (2014), we use data from the 1993 birth cohort and regress an indicator for college attendance at age 19 on parent income rank in each year from 1996 to 2012. We reproduce the coefficients from those regressions in Online Appendix Figure II Panel C. The relationship between college attendance rates and parent income rank is virtually constant when children are between ages 3 and 19. Once again, this result indicates that the point at which parent income is measured (provided parents are between ages 30–55) does not significantly affect intergenerational associations, at least in administrative earnings records.

### Atenuation Bias

Income in a single year is a noisy measure of lifetime income, which attenuates estimates of intergenerational persistence. To evaluate whether our baseline estimates suffer from such attenuation bias, Figure III Panel B plots estimates of the rank-rank slope, varying the number of years used to calculate mean parent family income. In this figure, we plot the slope from an OLS regression of child rank on parent rank, varying the number of years used to calculate mean parent income from one (1996 only) to 17 (1996–2012). The rank-rank slope based on five years of data (0.341) is 6.6% larger than the slope based on one year of parent income (0.320). We find that the rank-rank slope is virtually unchanged by adding more years of data beyond 5 years: the estimated slope using 15 years of data to measure parent income (0.350) is only 2.8% larger than the baseline slope of 0.341 using 5 years of data.

### Alternative Income Definitions

We define the parent’s rank based on the individual income of the parent with higher mean income from 1999 to 2003. This specification eliminates the mechanical variation in family income driven by the number of parents in the household, which could overstate the persistence of income across generations if parent marital status has a direct effect of children’s outcomes. The rank-rank correlation falls by approximately 10 percent, from 0.341 to 0.312 when we use top parent income. The impact of using individual parent income instead of family income is modest because (i) most of the variation in parent income across households is not due to differences in marital status and (ii) the mean ranks of children with married parents are only 4.6 percentile points higher than those with single parents.

Next, we consider alternative income definitions for the children. Here, one concern is that children of higher income parents may be more likely to marry, again exaggerating the observed persistence in family income relative to individual income. Using individual income to measure the child’s rank has differential impacts by the child’s gender. For male children, using individual income instead of family income reduces the rank-rank correlation from 0.336 in the baseline specification to 0.317, a 6 percent reduction. For female children, using individual income reduces the rank-rank correlation from 0.346 to 0.257, a 26 percent reduction. The change may be larger for women because women from high income families tend to marry high-income men and may choose not to work.

# Spatial Variation in Mobility

## Geographical Units

One way to conceptualize the choice of a geographical partition is using a hierarchical model in which children’s outcomes depend on conditions in their immediate neighborhood (such as peers or resources in their city block), local community (such as the quality of schools in their county), and broader metro area (such as local labor market conditions). To fully characterize the geography of intergenerational mobility, one would ideally estimate all of the components of such a hierarchical model. As a first step toward this goal, we characterize intergenerational mobility at the level of commuting zones.

We focus on CZ-level variation because mobility statistics in very small neighborhoods are likely to be heavily affected by sorting. Because property prices are typically homogeneous within narrow areas and home values are highly correlated with parent income, comparisons within a small neighborhood effectively condition on a proxy for parent income. As a result, the variation in parent income across individuals in a small area (such as a city block) must be correlated with other latent factors that could affect children’s outcomes directly, making it difficult to interpret the resulting mobility estimates. 

We permanently assign each child to a single CZ based on the ZIP code from which his or his parent filed their tax return in the first year the child was claimed as a dependent. We interpret this CZ as the area where a child grew up. Because our data begin in 1996, location is measured in 1996 for 95.9% of children in our
core sample. For children in our core sample of 1980–1982 birth cohorts, we therefore typically measure location when children were approximately 15 years old. For the children in the more recent birth cohorts in our extended sample, location is measured at earlier ages. Using these more recent cohorts, we find that 83.5 percent of children live in the same CZ at age 16 as they did at age 5. Furthermore, we verify that the spatial patterns for the outcomes we can measure at earlier ages (college attendance and teenage birth) are similar if we define CZs based on location at age 5 instead of age 16. The CZ where a child grew up does not necessarily correspond to the CZ he lives in as an adult when we measure his income (at age 30) in 2011–2012. In our core sample, 38% of children live in a different CZ in 2012 relative to where they grew up.


