---
title: "Intergenerational Mobility In Brazil"
subtitle: "Research Project"
author: "Lucas Warwar" 
date: "`r Sys.Date()`"
bibliography: 
output: 
  pdf_document:
    latex_engine: xelatex
citation_package: natbib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction and Motivation



## Policy Description (in case of evaluating a policy)



## Research Goals

  1. Individual-level full income distribution for Brazil (is RF's data complete?)
  2. Intergenerational income mobility: relationship between parent's and child's income ranks (+ race and gender?)
  3. Secondary outcomes: educational levels, employment, criminal charges
  4. Geographical variation: mobility measures accross IBGE's immediate regions - not causal (yet), sorting, endogeneity etc
  5. What is associated with mobility? Inequality, density, quality of education, marital status, social programs
  6. Place effects: sorting vs. causal --> families that move accross cities, exploit variation in age of child

## Methodology 

Rank-rank income mobility, P.Rank-secondary outcomes association

### Tasks
  1. Define timespan and cohorts
  2. Link parents to children (name? CadUnico? Censo Escolar? Tax?)
  3. Build income distribution for parents and children
  4. Construct mobility measures


## Data

  1. Income distribution: Tax records (timespan? additional info? keys to merge with other databases?)
  2. Educational outcomes: Censo Escolar? Enem? ProUni/Fies? 
  3. Labor market: RAIS
  4. Health outcomes (dataSUS)
  5. Social programs participations (CadUnico)
  6. City caractheristics: IBGE (city profile, demographics, sectoral share, migrations)

### Variables and Sources

| Variable              | Source        | Period | Notes   | Priority (0 = not necessary; 1 = optional; 2 = essential) |
|-----------------------|---------------|--------|---------|-----------------------------------------------------------|
| **Parental Income**   | Tax Records   | ???    |         | 2                                                         |
| Child Income          | Tax Records   | ???    |         | 2                                                         |
| High School Degree    | Censo Escolar | ???    |         | 1                                                         |
| Educ outcomes         | Censo Escolar | ???    |         | 1                                                         |
| College attendance    | RAIS?         | ???    |         | 0                                                         |
| Employment            | RAIS          | ???    |         | 1                                                         |
| Crime                 | Base Crimes?  | ???    |         | 0                                                         |





### Outcomes


### Controls

  
### Other 

## Literature Review

### Literature Theme

- @reference1 "Paper title abbreviation" 

    * Methodology: 
    * Main findings:
        + 
    * Mechanism: 
    * Extra: 
        + 


## References
